#!/usr/bin/env bash
# =============================================================================
#  publish-release.sh — mirror a release's binaries onto the Forgejo (primary)
#  and Codeberg forges.
#
#  Why this exists: Forgejo is the source of truth, while GitHub and Codeberg
#  are independent remotes synchronized during a release. Git pushes replicate
#  refs (branches/tags) — NOT release objects or binary assets. GitHub gets its
#  binaries from release.yml; this script attaches the same verified binaries
#  to Forgejo and Codeberg so all three forges carry the complete set.
#
#  Usage:
#     FJTOKEN=<forgejo-token> CBTOKEN=<codeberg-token> \
#         packaging/publish-release.sh v3.10.0 [asset-dir]
#
#   - <tag>       the release tag, e.g. v3.10.0 (must already be pushed).
#   - [asset-dir] a directory of files to attach. If omitted, the assets are
#                 downloaded from the GitHub release for <tag> using `gh`.
#
#  Tokens are read ONLY from the environment (never hard-coded / never printed):
#     FJTOKEN — Forgejo API token (git.securityops.com.br). Skips Forgejo if unset.
#     CBTOKEN — Codeberg API token.                        Skips Codeberg if unset.
#
#  Idempotent: reuses an existing release for the tag and skips any asset already
#  attached with the same byte size provisionally. Every remote asset is then
#  downloaded publicly and compared byte-for-byte with the validated local set.
#  Missing binaries, content/size mismatches, and API/download/upload errors fail.
#
#  Requires: Bash, curl, python3, cmp, and gh (only for auto-downloading assets).
#  License: GPL-3.0.
# =============================================================================
set -euo pipefail

# ---- forge coordinates (this project's actual setup) ------------------------
# git.securityops.co is retired (its account requires a password change, which
# blocks API auth); the live Forgejo instance is git.securityops.com.br.
FORGEJO_API="https://git.securityops.com.br/api/v1"
FORGEJO_OWNER="cristiancmoises"
CODEBERG_API="https://codeberg.org/api/v1"
CODEBERG_OWNER="berkeley"
REPO="turborec"
GITHUB_REPO="cristiancmoises/turborec"

log()  { printf '[publish] %s\n' "$*" >&2; }
die()  { printf '[publish] ERROR: %s\n' "$*" >&2; exit 1; }
need() { command -v "$1" >/dev/null 2>&1 || die "required tool not found: $1"; }

need curl
need python3
need cmp

TAG="${1:-}"
[ -n "${TAG}" ] || die "usage: FJTOKEN=… CBTOKEN=… $0 <tag> [asset-dir]"
VERSION="${TAG#v}"
[[ "${VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] \
    || die "tag must look like v3.10.0 (got: ${TAG})"
ASSET_DIR="${2:-}"

# ---- gather the assets ------------------------------------------------------
CLEANUP_DIR=""
VERIFY_DIR=""
cleanup() {
    if [ -n "${CLEANUP_DIR}" ]; then rm -rf -- "${CLEANUP_DIR}"; fi
    if [ -n "${VERIFY_DIR}" ]; then rm -rf -- "${VERIFY_DIR}"; fi
}
trap cleanup EXIT
if [ -z "${ASSET_DIR}" ]; then
    need gh
    ASSET_DIR="$(mktemp -d "${TMPDIR:-/tmp}/turborec-assets.XXXXXX")"
    CLEANUP_DIR="${ASSET_DIR}"
    log "downloading ${TAG} assets from the GitHub release…"
    gh release download "${TAG}" --repo "${GITHUB_REPO}" -D "${ASSET_DIR}"
fi
[ -d "${ASSET_DIR}" ] || die "asset dir not found: ${ASSET_DIR}"

# Collect the files to publish (regular files only).
ASSETS=()
# POSIX globs include hidden files without relying on GNU find extensions.
for f in "${ASSET_DIR}"/* "${ASSET_DIR}"/.[!.]* "${ASSET_DIR}"/..?*; do
    if [ -f "${f}" ] && [ ! -L "${f}" ]; then ASSETS+=("${f}"); fi
done
[ "${#ASSETS[@]}" -gt 0 ] || die "no asset files in ${ASSET_DIR}"
log "found ${#ASSETS[@]} asset(s) to publish for ${TAG}"

# Mirror exactly the public release manifest, never arbitrary local files.
EXPECTED=(
    "SHA256SUMS"
    "Turbo_Recorder-${VERSION}-windows-x64.exe"
    "Turbo_Recorder-${VERSION}-windows-x64-setup.exe"
    "Turbo_Recorder-${VERSION}-x86_64.AppImage"
    "turborec-${VERSION}-1.noarch.rpm"
    "turborec-${VERSION}-1.src.rpm"
    "turborec-${VERSION}-guix-x86_64.zupt"
    "turborec-${VERSION}.pkg"
    "turborec-${VERSION}-source.zupt"
    "turborec-${VERSION}.zupt"
    "turborec_${VERSION}_all.deb"
)
for name in "${EXPECTED[@]}"; do
    if [ ! -f "${ASSET_DIR}/${name}" ] || [ -L "${ASSET_DIR}/${name}" ] \
        || [ ! -s "${ASSET_DIR}/${name}" ]; then
        die "missing, empty, or non-regular required asset: ${name}"
    fi
done
[ "${#ASSETS[@]}" -eq "${#EXPECTED[@]}" ] \
    || die "asset directory contains unexpected files"
# Compare individual names, not newline-flattened text: filenames may contain
# newlines and must never alias multiple expected assets.
for f in "${ASSETS[@]}"; do
    matched=0
    for name in "${EXPECTED[@]}"; do
        if [ "${f##*/}" = "${name}" ]; then matched=1; break; fi
    done
    [ "${matched}" -eq 1 ] || die "asset directory contains unexpected files"
done
# Python is already required and provides portable SHA-256 on macOS/BSD too.
# Accept the GNU checksum format generated by release.yml, but only for the
# exact ten payloads: no missing, duplicate, or arbitrary-path entries.
python3 -c '
import hashlib, pathlib, re, sys
directory = pathlib.Path(sys.argv[1])
expected = set(sys.argv[2:])
checksums = {}
for line in (directory / "SHA256SUMS").read_text(encoding="ascii").splitlines():
    digest, name = line[:64], line[66:]
    if not re.fullmatch(r"[0-9a-fA-F]{64}", digest) or line[64:66] not in ("  ", " *"):
        sys.exit("invalid SHA256SUMS format")
    if name not in expected or name in checksums:
        sys.exit("unexpected or duplicate SHA256SUMS entry")
    checksums[name] = digest.lower()
if set(checksums) != expected:
    sys.exit("missing required SHA256SUMS entry")
for name, expected_digest in checksums.items():
    digest = hashlib.sha256()
    with (directory / name).open("rb") as source:
        for block in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(block)
    if digest.hexdigest() != expected_digest:
        sys.exit("checksum mismatch for " + name)
    print(name + ": OK")
' "${ASSET_DIR}" "${EXPECTED[@]:1}" \
    || die "release checksum verification failed"
VERIFY_DIR="$(mktemp -d "${TMPDIR:-/tmp}/turborec-verify.XXXXXX")" \
    || die "could not create private verification directory"

# ---- release notes: reuse the GitHub release body when available ------------
NOTES=""
if command -v gh >/dev/null 2>&1; then
    NOTES="$(gh release view "${TAG}" --repo "${GITHUB_REPO}" \
             --json body --jq '.body' 2>/dev/null || true)"
fi
[ -n "${NOTES}" ] || NOTES="Turbo Recorder ${TAG}"

# ---- helper: publish to one Gitea/Forgejo-family forge ----------------------
# args: <label> <api-base> <owner> <token>
publish_to() {
    local label="$1" api="$2" owner="$3" token="$4"
    local base="${api}/repos/${owner}/${REPO}"
    local origin="${api%/api/v1}"
    # Feed the auth header on stdin, keeping the token out of process arguments.
    [[ "${token}" =~ ^[A-Za-z0-9_]+$ ]] || die "invalid token format"
    auth_curl() {
        # Only fixed-origin API requests receive auth. Never follow redirects;
        # disabling curlrc prevents user configuration from adding that behavior.
        [[ "${!#}" == "${api}/"* ]] || return 1
        printf 'header = "Authorization: token %s"\n' "${token}" \
            | curl --disable --config - --proto '=https' \
                --connect-timeout 30 --max-time 3600 "$@"
    }

    log "── ${label} ────────────────────────────────────────────"

    # Preflight: the forge's git tag ref must exist AND match the local tag.
    # A stale force-mirror can delete or re-anchor newer tags (observed with
    # git.securityops.co wiping main + v3.7.1/v3.8.1 off GitHub); publishing
    # against the wrong ref would anchor the release on an old commit. Skip
    # the check when run outside the repository (no local tag to compare).
    local local_sha=""
    if git rev-parse -q --verify "refs/tags/${TAG}" >/dev/null 2>&1; then
        local_sha="$(git rev-parse "refs/tags/${TAG}")"
    fi
    if [ -n "${local_sha}" ]; then
        local remote_sha=""
        remote_sha="$(auth_curl -fsS "${base}/git/refs/tags/${TAG}" 2>/dev/null \
            | python3 -c 'import sys,json
d=json.load(sys.stdin)
if isinstance(d, list):        # Gitea returns a one-element array here
    d = d[0] if d else {}
print(d.get("object",{}).get("sha",""))' 2>/dev/null || true)"
        if [ -z "${remote_sha}" ] || [ "${remote_sha}" != "${local_sha}" ]; then
            log "${label}: tag ${TAG} is missing or mismatched on the forge"
            log "  remote=${remote_sha:-missing}  local=${local_sha}  (stale mirror?) — refusing to publish"
            return 1
        fi
        log "${label}: tag ${TAG} ref verified (${local_sha})"
    fi

    # Reuse an existing release for the tag, else create one.
    local rid
    rid="$(auth_curl -fsS "${base}/releases/tags/${TAG}" 2>/dev/null \
           | python3 -c 'import sys,json;print(json.load(sys.stdin).get("id",""))' 2>/dev/null || true)"
    if [ -z "${rid}" ]; then
        local payload
        payload="$(NOTES="${NOTES}" TAG="${TAG}" python3 -c \
          'import os,json;print(json.dumps({"tag_name":os.environ["TAG"],"name":"Turbo Recorder "+os.environ["TAG"].lstrip("v"),"body":os.environ["NOTES"],"draft":False,"prerelease":False}))')"
        rid="$(auth_curl -fsS -X POST -H "Content-Type: application/json" \
               -d "${payload}" "${base}/releases" \
               | python3 -c 'import sys,json;d=json.load(sys.stdin);print(d.get("id") or "")')"
        [ -n "${rid}" ] || {
            log "${label}: could not create release"
            return 1
        }
        log "${label}: created release id=${rid}"
    else
        log "${label}: reusing release id=${rid}"
    fi

    # Existing name/size pairs provisionally skip uploads, but do not establish
    # identity. Final verification below checks every asset's actual bytes.
    local existing
    existing="$(auth_curl -fsS "${base}/releases/${rid}" \
               | python3 -c 'import sys,json;print("\n".join("{}\t{}".format(a["name"],a.get("size",0)) for a in json.load(sys.stdin).get("assets",[])))' 2>/dev/null || true)"

    local f name code local_size remote_size failures=0
    for f in "${ASSETS[@]}"; do
        name="$(basename "${f}")"
        local_size="$(wc -c < "${f}" | tr -d '[:space:]')"
        remote_size="$(printf '%s\n' "${existing}" \
            | awk -F '\t' -v wanted="${name}" '$1 == wanted { print $2; exit }')"
        if [ -n "${remote_size}" ]; then
            if [ "${remote_size}" = "${local_size}" ]; then
                log "  = ${name} (same size; content verification pending)"
                continue
            fi
            log "  ! ${name} has remote size ${remote_size}, expected ${local_size}"
            failures=$((failures + 1))
            continue
        fi
        # --http1.1 avoids HTTP/2 framing errors some servers hit on large
        # uploads; a failed upload must not abort the whole run (|| code=000),
        # so remaining assets and the other forge still get published.
        code="$(auth_curl -s -o /dev/null -w '%{http_code}' --http1.1 --max-time 3600 \
               -X POST \
               -F "attachment=@${f};filename=${name}" \
               "${base}/releases/${rid}/assets?name=${name}")" || code="000"
        # Some Forgejo reverse proxies reject otherwise valid release
        # attachments based on the multipart filename/MIME type (notably RPM,
        # AppImage, and extensionless checksum files).  The API's `name` query
        # parameter is the authoritative public filename, so retry a 403 using
        # neutral transport metadata while preserving the exact remote name and
        # every byte of the original file.
        if [ "${code}" = "403" ]; then
            code="$(auth_curl -s -o /dev/null -w '%{http_code}' --http1.1 --max-time 3600 \
                   -X POST \
                   -F "attachment=@${f};filename=turborec-release-asset.zupt;type=application/octet-stream" \
                   "${base}/releases/${rid}/assets?name=${name}")" || code="000"
        fi
        if [ "${code}" = "201" ]; then
            log "  + ${name}"
        else
            log "  ! ${name} FAILED (HTTP ${code})"
            failures=$((failures + 1))
        fi
    done

    # Re-read authoritative metadata, then compare all public downloads to the
    # locally checksum-validated bytes (including SHA256SUMS). No token goes to
    # asset URLs or follows redirects; public redirects may only use HTTPS.
    local metadata download_url
    if ! metadata="$(auth_curl -fsS "${base}/releases/${rid}")"; then
        log "${label}: could not read release for content verification"
        return 1
    fi
    for f in "${ASSETS[@]}"; do
        name="$(basename "${f}")"
        local_size="$(wc -c < "${f}" | tr -d '[:space:]')"
        if ! download_url="$(printf '%s' "${metadata}" | python3 -c '
import json, sys
name, size, origin = sys.argv[1:]
matches = [a for a in json.load(sys.stdin).get("assets", []) if a.get("name") == name]
if len(matches) != 1 or str(matches[0].get("size")) != size:
    sys.exit(1)
url = matches[0].get("browser_download_url")
# Exact origin plus slash excludes userinfo and lookalike/foreign hosts.
if not isinstance(url, str) or not url.startswith(origin + "/"):
    sys.exit(1)
if any(ord(c) <= 32 or ord(c) == 127 for c in url):
    sys.exit(1)
print(url)
' "${name}" "${local_size}" "${origin}" 2>/dev/null)"; then
            log "  ! verification failed for ${name} (missing asset, size mismatch, or invalid public URL)"
            failures=$((failures + 1))
            continue
        fi
        if ! curl --disable --fail --silent --show-error --location \
            --proto '=https' --proto-redir '=https' --retry 3 \
            --connect-timeout 30 --max-time 3600 \
            -o "${VERIFY_DIR}/${name}" "${download_url}"; then
            log "  ! public download failed for ${name}"
            failures=$((failures + 1))
        elif ! cmp -s -- "${f}" "${VERIFY_DIR}/${name}"; then
            log "  ! remote content mismatch for ${name}"
            failures=$((failures + 1))
        else
            log "  ✓ ${name} (remote content verified)"
        fi
    done
    [ "${failures}" -eq 0 ]
}

# ---- run for each forge that has a token ------------------------------------
did_any=0
failed=0
if [ -n "${FJTOKEN:-}" ]; then
    if ! publish_to "Forgejo (primary)" "${FORGEJO_API}" "${FORGEJO_OWNER}" "${FJTOKEN}"; then
        failed=1
    fi
    did_any=1
else log "FJTOKEN not set — skipping Forgejo"; fi
if [ -n "${CBTOKEN:-}" ]; then
    if ! publish_to "Codeberg" "${CODEBERG_API}" "${CODEBERG_OWNER}" "${CBTOKEN}"; then
        failed=1
    fi
    did_any=1
else log "CBTOKEN not set — skipping Codeberg"; fi

[ "${did_any}" = "1" ] || die "no forge tokens set (FJTOKEN / CBTOKEN) — nothing to do"
[ "${failed}" = "0" ] || die "one or more forge uploads failed verification"
log "done."
